### ISSUE TITLE
GitVersion: Mainline doesn't yet support pre-release tags.

### ISSUE THREAD

**Issue by Joll59** [Azure-Samples/Speech-Service-DevOps-Template#57]
![image](https://user-images.githubusercontent.com/16693765/83545478-e7ef8200-a4c4-11ea-9c5d-1831f7933fd6.png)

When running workflow in a branch, the pipeline fails because there is a previous release with a pre-release semver and GitVersions versioning mode is set to mainline. Results in the error above.  

Current working solution is to delete those tags via command line with 

`git push --delete origin tagname`

**Comment by cmayomsft** [comment]
We've tested this from scratch an we could not repo the problem. We're going to close.
